<!DOCTYPE html>
<html>
<head>
    <title>Under Maintenance - Atharvdeep</title>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Nunito:400,600,700,800" rel="stylesheet">
    <link rel="icon" href="images/favicon.ico">
    <style type="text/css">
        *{
            margin: 0;
            padding: 0;
        }
        body{
            font-family: 'Nunito', sans-serif;
        }
        main{
            width: 80%;
            height: auto;
            display: block;
            margin: 0 auto;
            padding-top: 150px;
        }
        main:after{
            content: '';
            display: block;
            clear: both;
        }
        article{
            width: 30%;
            float: left;
        }
        img{
            display: block;
            max-width: 100%;
            height: auto;
            width: 200px;
            margin: 0 auto;
        }
        aside{
            width: 70%;
            float: left;
        }
        h1{
            font-size: 30px;
            font-weight: 600;
            padding: 15px 0;
            margin: 0;
        }
        p{
            font-size: 16px;
            font-weight: 400;
            padding: 0;
        }
        a{
            color: #e95110;
            text-decoration: none;
        }
        a:hover{
            color: #472d5d;
        }
        @media only screen and (max-width: 768px) {
            article, aside{
                width: 100%;
                float: none;
            }
            main{
                padding-top: 70px;
            }
            h1{
                font-size: 24px;
            }
            img{
                width: 150px;
            }
        }
        @media screen and (min-width: 769px) and (max-width: 991px) {
            h1{
                padding: 0 0 0 20px;
            }
            p{
                padding-left: 20px;
            }
        }
    </style>
</head>

<body>
    <main>
        <article>
            <img src="../../media/wysiwyg/fasony/home01/Original_logo.jpg">
        </article>
        <aside>
            <h1>Something amazing is lined up for you. Stay tuned!</h1>
            <p>Sorry for the inconvenience caused as we are performing the scheduled maintenance of the website. We will be back in an hour with amazing features and product updates. Meanwhile if you need any help you can <a href="mailto:atharvdeep46@gmail.com">contact us</a> as we are always there to help our members.</p>
            <p>&mdash; Team Atharvdeep</p>
        </aside>
    </main>
</body>
</html>
