<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * stories sidebar recent posts template
 *
 * @var $block \Magefan\Stories\Block\Sidebar\Recent
 */
?>

<?php
	$_postCollection = $block->getPostCollection();
	$_helper = $this->helper('Magefan\Stories\Helper\Image');
?>
<?php if ($_postCollection->count()) { ?>
<div class="widget block block-static-block">
    <div class="row">
		<div class="col-sm-24">
			<div class="em-wrapper-ads-10 em-line-01">
				<div class="em-block-title">
					<h2><span><?php echo __('Stories') ?></span></h2>
				</div>
				<div class="em-from-our-stories">
					<?php foreach ($_postCollection as $_post) { ?>
					<?php
						$time = strtotime($_post->getData('publish_time'));
					?>
					<div class="em-stories-item em-effect-13">
						<div class="em-stories-content bkg-top">
							<a href="<?php echo $_post->getPostUrl() ?>">
								<img class="img-responsive" src="<?php echo $_helper->init($_post->getImage())->resize(280); ?>" alt="<?php echo $_post->getTitle() ?>">
							</a>
							<div class="em-stories-time">
								<p class="em-stories-date"><?php echo date('d',$time)?></p>
								<p class="em-stories-month"><?php echo date('M',$time)?></p>
							</div>
							<div class="hov">&nbsp;</div>
						</div>
						<div class="em-box bkg-bottom">
							<h4 class="em-stories-title"><a href="<?php echo $_post->getPostUrl() ?>"><?php echo $block->escapeHtml($_post->getTitle()) ?></a></h4>
							<p class="em-stories-des">
								<?php echo $block->short($_post->getShortDescription()) ?>
							</p>
							<p><a class="link-more" href="<?php echo $_post->getPostUrl() ?>"><?php echo __('Read more') ?></a></p>
						</div>
					</div>
					<?php } ?>
				</div>
			</div>
		</div>
	</div>
</div>
<?php } ?>


