<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * stories post list toolbar template
 *
 * @var $block \Magefan\Stories\Block\Post\PostList\Toolbar
 */
?>

<?php if ($block->getCollection()->getSize()): ?>
    <div class="toolbar toolbar-stories-posts">
        <?php echo $block->getPagerHtml() ?>
    </div>
<?php endif ?>
