<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Storiesrelated posts template
 *
 * @var $block \Magefan\Stories\Block\Post\View\RelatedProducts
 */
?>

<?php
if ($exist = $block->getItems()->getSize() && $this->displayProducts()) {
    $type = 'related';
    $class = $type;

    $image = 'related_products_list';
    $title = __('Related Products');
    $items = $block->getItems();
    $limit = 0;
    $shuffle = 0;
    $canItemsAddToCart = true;

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = null;
    $description = false;
}
$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
?>

<?php if ($exist):?>

    <?php if ($type == 'related' || $type == 'upsell'): ?>
        <?php if ($type == 'related'): ?>
            <div class="block <?php echo $class; ?>" data-mage-init='{"relatedProducts":{"relatedCheckbox":".related.checkbox"}}' data-limit="<?php echo $limit; ?>" data-shuffle="<?php echo $shuffle; ?>">
        <?php else: ?>
            <div class="block <?php echo $class; ?>" data-mage-init='{"upsellProducts":{}}' data-limit="<?php echo $limit; ?>" data-shuffle="<?php echo $shuffle; ?>">
        <?php endif; ?>
    <?php else: ?>
        <div class="block <?php echo $class; ?>">
    <?php endif; ?>
    <div class="block-title title">
        <strong id="block-<?php echo $class?>-heading" role="heading" aria-level="2"><?php echo $title; ?></strong>
    </div>
    <div class="block-content content" aria-labelledby="block-<?php echo $class?>-heading">

        <div class="products wrapper grid products-grid products-<?php echo $type; ?>">
<ol class="products list items product-items">
<?php $iterator = 1; ?>
<?php foreach ($items as $_item): ?>
<?php $available = ''; ?>
<?php if (!$_item->isComposite() && $_item->isSaleable() && $type == 'related'): ?>
<?php if (!$_item->getRequiredOptions()): ?>
<?php $available = 'related-available'; ?>
<?php endif; ?>
<?php endif; ?>
<?php if ($type == 'related' || $type == 'upsell'): ?>
<?php echo($iterator++ == 1) ? '<li class="item product product-item" >' : '</li><li class="item product product-item" >' ?>
<?php else: ?>
<?php echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
<?php endif; ?>
<div class="product-item-info <?php echo $available; ?>">
<?php echo '<!-- ' . $image . '-->' ?>
<a href="<?php echo $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
<?php echo $block->getImage($_item, $image)->toHtml(); ?>
</a>
<div class="product details product-item-details">
<strong class="product name product-item-name"><a class="product-item-link" title="<?php echo $block->escapeHtml($_item->getName()) ?>" href="<?php echo $block->getProductUrl($_item) ?>">
<?php echo $block->escapeHtml($_item->getName()) ?></a>
</strong>

<?php echo $block->getProductPrice($_item); ?>

<?php if ($templateType): ?>
<?php echo $block->getReviewsSummaryHtml($_item, $templateType) ?>
<?php endif; ?>

<?php if ($showWishlist || $showCompare || $showCart): ?>
<div class="product actions product-item-actions">
<?php if ($showCart): ?>
<div class="actions-primary">
    <?php if ($_item->isSaleable()): ?>
        <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
            <button onclick="javascript:_paq.push(['trackEvent', 'BlogPostViewPage', 'buyInRelatedProductsFromBlogPostViewPage'],'<?php echo $block->escapeHtml($_item->getName()) ?>');" class="action tocart primary" data-mage-init='{"redirectUrl": {"url": "<?php echo $block->getAddToCartUrl($_item) ?>"}}' type="button" title="<?php  echo __('Add to Cart') ?>">
                <span><?php echo __('Add to Cart') ?></span>
            </button>
        <?php else: ?>
            <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
            $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
            ?>
            <button class="action tocart primary"
                    data-post='<?php echo $postData; ?>'
                    type="button" title="<?php echo __('Add to Cart') ?>">
                <span><?php echo __('Add to Cart') ?></span>
            </button>
        <?php endif; ?>
    <?php else: ?>
        <?php if ($_item->getIsSalable()): ?>
            <div class="stock available"><span><?php echo __('In stock') ?></span></div>
        <?php else: ?>
            <div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
        <?php endif; ?>
    <?php endif; ?>
</div>
<?php endif; ?>

<?php if ($showWishlist || $showCompare): ?>
<div class="secondary-addto-links actions-secondary" data-role="add-to-links">
    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $showWishlist): ?>
        <a href="#" onclick="javascript:_paq.push(['trackEvent', 'BlogPostViewPage', 'addToMyListInRelatedProductsFromBlogPostViewPage','<?php echo $block->escapeHtml($_item->getName()) ?>']);" data-post='<?php echo $block->getAddToWishlistParams($_item); ?>'  class="action towishlist" data-action="add-to-wishlist" title="My List">
            <span><?php echo __('Add to Wish List') ?></span>
        </a>
    <?php endif; ?>
    <!-- 25-05-2017 - udayp - show share icons in related products -->
    <?php $productAltImage = $_imagehelper->init($_item, 'product_small_image'); ?>
    <div id="share_me" onclick="javascript:_paq.push(['trackEvent', 'BlogPostViewPage', 'shareInRelatedProductsFromBlogPostViewPage','<?php echo $block->escapeHtml($_item->getName()) ?>']);" title="Share" class="share_me"><span class="icon-facebook fa fa-share-alt"></span>
        <p id="sharers">
            <a class="em-social-icon em-facebook" onclick="javascript:_paq.push(['trackEvent', 'BlogPostViewPage', 'facebookShareInRelatedProductsFromBlogPostViewPage','<?php echo $block->escapeHtml($_item->getName()) ?>']);" href="https://www.facebook.com/sharer/sharer.php?u=<?php echo $block->getProductUrl($_item) ?>&t=Homelot Fine Products" target="_blank" title="Facebook"><button><span class="icon-facebook fa fa-facebook"></span></button></a>
            <a class="em-social-icon em-facebook" onclick="javascript:_paq.push(['trackEvent', 'BlogPostViewPage', 'pinterestShareInRelatedProductsFromBlogPostViewPage','<?php echo $block->escapeHtml($_item->getName()) ?>']);" href="https://pinterest.com/pin/create/button/?url=<?php echo $block->getProductUrl($_item); ?>&media=<?php echo $productAltImage->getUrl();?>&description=<?php echo $_item->getName(); ?>" target="_blank" title="Pinterest"><button><span class="icon-pinterest fa fa-pinterest-square"></span></button></a>
        </p>
    </div>
    <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
        <?php
        $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
        ?>
        <a href="#" class="action tocompare"
           data-post='<?php echo $compareHelper->getPostDataParams($_item);?>'
           data-role="add-to-links"
           title="<?php echo __('Add to Compare'); ?>">
            <span><?php echo __('Add to Compare') ?></span>
        </a>
    <?php endif; ?>
</div>
<?php endif; ?>
</div>
<?php endif; ?>
</div>
</div>
<?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
<?php endforeach ?>
</ol>
        </div>
    </div>
</div>
<?php endif;?>